<!--<div class="row">-->
<!--    <div class="col-lg-6 bg-primary">reaygre</div>-->
<!--    <div class="col-lg-6 bg-warning">aewyew</div>-->
<!--</div>-->

<!--<div class="container_footer">-->
<!--    <div class="row footer-top">-->
<!--        <div class="col-lg-5">-->
<!--            <div class="row">-->
<!--                <div class="col-md-4">-->
<!--                    <a href="#" class="logo"><img src="--><?php //echo $this->getViewFileUrl('images/logo.svg'); ?><!--"></a>-->
<!--                </div>-->
<!--                <div class="col-md-8">-->
<!--                        <p class="title_footer">Questions?</p>-->
<!--                        <div class="links">-->
<!--                            <a href="tel:1-888-123-456" class="phone">1-888-123-456</a>&emsp; <div class="vr"></div> &emsp; &emsp;-->
<!--                            <a href="#" class="social-icon mt-5 mx-4"><i class="fab fa-facebook-f"></i></a>&emsp; &emsp;-->
<!--                            <a href="#" class="social-icon"><i class="fab fa-twitter"></i></a>&emsp;&emsp;-->
<!--                            <a href="#" class="social-icon"><i class="fab fa-linkedin-in"></i></a>&emsp;&emsp;-->
<!--                            <a href="#" class="social-icon"><i class="fab fa-instagram"></i></a>-->
<!--                        </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="col-lg-7">-->
<!--            <div class="row">-->
<!--                <div class="col-md-4">-->
<!--                    <p class="title_footer">Account</p>-->
<!--                    <div class="widget_content">-->
<!--                        <a href="#">My Account</a><br>-->
<!--                        <a href="#">Track Your Order</a><br>-->
<!--                        <a href="#">Payment Methods</a><br>-->
<!--                        <a href="#">Shipping Guide</a>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-md-4">-->
<!--                    <p class="title_footer">About</p>-->
<!--                    <div class="widget_content">-->
<!--                        <a href="#">About Porto</a><br>-->
<!--                        <a href="#">Our Guarantees</a><br>-->
<!--                        <a href="#">Terms And Conditions</a><br>-->
<!--                        <a href="#">Privacy Policy</a>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-md-4">-->
<!--                    <p class="title_footer">Features</p>-->
<!--                    <div class="widget_content">-->
<!--                        <a href="#">Powerful Admin Panel</a><br>-->
<!--                        <a href="#">Mobile & Retina Optimized</a><br>-->
<!--                        <a href="#">Super Fast Porto Theme</a><br>-->
<!--                        <a href="#">1st Fully working Ajax Theme</a>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!---->
<!--    <hr class="hr">-->
<!---->
<!--    <div class="footer-bottom col-sm">-->
<!--        <div class="footer_left"><p>© Copyright 2020. All Rights Reserved.</p></div>-->
<!--        <div class="footer_right"><img class="footer_right" src="--><?php //echo $this->getViewFileUrl('images/payment_icons.png'); ?><!--"></div>-->
<!--    </div>-->
<!--</div>-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<style>
    li {
        list-style: none;
    }

    h3.widget-title {
        margin-left: 41px;
    }

    .widget-content ul li a {
        color: #9e9696;
    }
    ul {
        list-style: none;
    }
    .widget {
        font-family: none;
        font-size: 14px;
    }
    .logo{
        margin-top: 10px;
    }
</style>
<div class="container">
    <div class="footer-top row row-sm">
        <div class="col-lg-5 col-xl-6">
            <div class="row row-sm" style="display: flex; align-items: center;">
                <div class="col-md-4 col-lg-12 col-xl-4">
                    <a href="index.html" class="logo"><img src="<?php echo $this->getViewFileUrl('images/logo.svg'); ?>"></a>
                </div>
                <div class="col-md-8 col-lg-12 col-xl-8">
                    <div class="social-link">
                        <h4>Questions?</h4>
                        <div class="links">
                            <a href="tel:1-888-123-45" class="phone_link">1-888-123-456</a>
                            <hr class="vertical">
                            <div class="social-icons">
                                <a href="#" target="_blank" class="social-icon"><i class="fab fa-facebook-f"></i></a>
                                <a href="#" target="_blank" class="social-icon"><i class="fab fa-twitter"></i></a>
                                <a href="#" target="_blank" class="social-icon"><i class="fab fa-linkedin-in"></i></a>
                                <a href="#" target="_blank" class="social-icon"><i class="icon-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-7 col-xl-6">
            <div class="row row-sm">
                <div class="col-md-4 col-lg-4">
                    <div class="widget">
                        <h3 class="widget-title">Account</h3>
                        <div class="widget-content">
                            <ul>
                                <li><a href="my-account.html">My Account</a></li>
                                <li><a href="#">Track Your Order</a></li>
                                <li><a href="#">Payment Methods</a></li>
                                <li><a href="#">Shipping Guide</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-4">
                    <div class="widget">
                        <h3 class="widget-title">About</h3>
                        <div class="widget-content">
                            <ul>
                                <li><a href="about.html">About Porto</a></li>
                                <li><a href="#">Our Guarantees</a></li>
                                <li><a href="#">Terms And Conditions</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-4">
                    <div class="widget">
                        <h3 class="widget-title">Features</h3>
                        <div class="widget-content">
                            <ul>
                                <li><a href="#">Powerful Admin Panel</a></li>
                                <li><a href="#">Mobile &amp; Retina Optimized</a></li>
                                <li><a href="#">Super Fast Porto Theme</a></li>
                                <li><a href="#">1st Fully working Ajax Theme</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr style="background-color: #e4e4e4; height: 1px">
    <div class="footer-bottom">
        <p style="width: 40%;float: left;">© 2020. All Rights Reserved</p>
        <img src="<?php echo $this->getViewFileUrl('images/payment_icons.png'); ?>" style="float: right;">
    </div>
</div>
