<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('css/style1.css')?>">
<div class="item1" style="background-color: black; margin-top:1rem;">
    <img style="margin: 3.5%" src="<?php echo $this->getViewFileUrl('images/brand1.png'); ?>">
    <img style="" src="<?php echo $this->getViewFileUrl('images/brand2.png'); ?>">
    <img style="margin-left: 5%;" src="<?php echo $this->getViewFileUrl('images/brand3.png'); ?>">
    <img style="margin-left: 5%;" src="<?php echo $this->getViewFileUrl('images/brand4.png'); ?>">
    <img style="margin-left: 5%;" src="<?php echo $this->getViewFileUrl('images/brand5.png'); ?>">
    <img style="margin-left: 5%;" src="<?php echo $this->getViewFileUrl('images/brand6.png'); ?>">
</div>
