<hr style="background-color: #e4e4e4; height: 1px">
<div class="col-md-6 col-lg-3">
            <div class="service-widget">
                <img src="<?php echo $this->getViewFileUrl('images/truck.png'); ?>" width="56" height="56" alt="truck">
                <div class="service-content">
                    <h3 class="service-title">free shipping &amp; return</h3>
                    <p>Free shipping on all orders over $99.</p>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-3">
            <div class="service-widget">
                <img src="<?php echo $this->getViewFileUrl('images/dollar.png'); ?>" width="56" height="56" alt="truck">
                <div class="service-content">
                    <h3 class="service-title">money back guarantee</h3>
                    <p>100% money back guarantee</p>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-3">
            <div class="service-widget">
                <img src="<?php echo $this->getViewFileUrl('images/time.png'); ?>" width="56" height="56" alt="truck">
                <div class="service-content">
                    <h3 class="service-title">online support 24/7</h3>
                    <p>Lorem ipsum dolor sit amet.</p>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-3">
            <div class="service-widget">
                <img src="<?php echo $this->getViewFileUrl('images/cart.png'); ?>" width="56" height="56" alt="truck">
                <div class="service-content">
                    <h3 class="service-title">secure payment</h3>
                    <p>Loerm isum dolor sit amet.</p>
                </div>
            </div>
        </div>
<hr style="background-color: #e4e4e4; height: 1px">
