<div class="grid-item col-lg-5 height-x1" style="position: absolute; left: 0%; top: 0px;">
    <div class="home-banner">
        <figure>
            <img src="<?php echo $this->getViewFileUrl('home-banner1.jpg'); ?>" />
        </figure>
        <div class="banner-content content-right">
            <h3><strong>black<br></strong>Armchairs</h3>
            <p>starting from $399</p>
            <button class="btn">shop now <i class="fas fa-long-arrow-alt-right"></i></button>
        </div>
    </div>
</div>
<div class="grid-item col-lg-7 height-x2" style="position: absolute; left: 0%; top: 335px;">
    <div class="home-banner">
        <figure>
            <img src="assets/images/banners/home-banner2.jpg">
        </figure>
        <div class="banner-content content-left">
            <h3><strong>wooden<br></strong>Black Chair</h3>
            <div class="banner-info">
                <a href="#" class="btn skew-box">go coupon</a>
                <h3 class="sale-off skew-box"><span>$100</span>off</h3>
                <p>starting from $199</p>
                <button class="btn">shop now <i class="fas fa-long-arrow-alt-right"></i></button>
            </div>
        </div>
    </div>
</div>
<div class="grid-item col-6 col-lg-2 height-x1" style="position: absolute; left: 0%; top: 1005px;">
    <div class="home-banner">
        <figure>
            <img src="assets/images/banners/home-banner3.jpg">
        </figure>
        <div class="banner-content content-top">
            <span>check new arrivals</span>
            <h4><strong>cool lamps</strong></h4>
        </div>
    </div>
</div>
<div class="grid-item col-6 col-lg-3 height-x1" style="position: absolute; left: 49.9988%; top: 1005px;">
    <div class="home-banner">
        <figure>
            <img src="assets/images/banners/home-banner4.jpg">
        </figure>
        <div class="banner-content content-bottom">
            <span>exclusive new collection</span>
            <h4><strong>luxurious jacuzzi</strong></h4>
        </div>
    </div>
</div>
<hr class="mt-0">

