<?php
use Magento\Catalog\Block\Product\ReviewRendererInterface;

/**
 * @var \BestSeller\Seller\Block\widget\ $block
 */
if ($exist = ($this->getBestsellerProduct() && $this->getBestsellerProduct()->getPageSize())) {
    $fet_prodcollection = $this->getBestsellerProduct();
    $productcount = $this->getProductLimit();
    $imagewidth = $this->getProductimagewidth();
    $imageheight = $this->getProductimageheight();
    $mode = 'grid';
    $title = __('Bestseller Products');
    $type = 'widget-bestseller-grid';
    $image = 'bestseller_products_content_widget_grid';
}
$templateType = ReviewRendererInterface::SHORT_VIEW;
?>



<?php if ($exist):?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <div class="block widget block-bestseller-products <?php /* @escapeNotVerified */ echo $mode; ?>">

        <?php if (!$fet_prodcollection->count()): ?>
            <div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
        <?php else: ?>
            <div class="block-content">
                <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                    <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                        <?php $iterator = 1; ?>
                        <?php foreach ($fet_prodcollection as $item):
                            $_product = $this->getLoadProduct($item->getProductId());
                            ?>
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                            <div class="product-item-info">
                                <?php
                                $image_url = $block->imageHelperObj()->init($_product, 'product_page_image_small')
                                    ->setImageFile($_product->getFile())
                                    ->resize($imagewidth,$imageheight)
                                    ->getUrl();
                                ?>
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-item-photo">
                                    <img src="<?php echo  $image_url;?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
                                </a>


                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a title="<?php echo $block->escapeHtml($_product->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-item-link">
                                            <?php echo $block->escapeHtml($_product->getName()) ?>
                                        </a>
                                    </strong>
                                    <?php
                                    echo $this->getProductPriceHtml($_product, $type);
                                    ?>
                                    <div class="product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>

                                                <?php else: ?>
                                                    <?php
                                                    $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getId()]);
                                                    ?>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php echo($iterator == count($fet_prodcollection)+1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        <div class="buttonBrowse" style="text-align: center">
            <button class="btnBrowseAll" style="background-color: white; height: 50px; width: 140px"> BROWSE ALL <i class="fa fa-arrow-right"></i></button>
        </div>
            <script type="">
                $(document).ready(function(){
                    $('.btnBrowseAll').click(function(){
                        window.location.replace('/bestseller');
                    });
                });
            </script>
        <?php endif; ?>
    </div>
<?php endif;?>
